# Generated by Django 5.2.11 on 2026-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200529_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, db_column='product_image', null=True, upload_to='products/'),
        ),
    ]
