# Generated by Django 6.0.2 on 2026-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_orderdetails_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(db_column='payment_status', default='Chờ thanh toán', max_length=20),
        ),
    ]
